package com.booksys.concierge;

public enum ConciergeType {
    TAXI_TRANSFER,
    RESTAURANT_RESERVATION,
    TOUR_EXCURSION,
    WAKE_UP_CALL,
    LUGGAGE_STORAGE,
    ROOM_SERVICE,
    SPA_APPOINTMENT,
    CAR_RENTAL,
    AIRPORT_PICKUP,
    FLOWER_ARRANGEMENT,
    BIRTHDAY_PACKAGE,
    BUSINESS_SERVICES,
    LAUNDRY,
    MEDICAL_ASSISTANCE,
    OTHER
}
